### ISSUE TITLE
URL refers to root and not subdirectory

### ISSUE THREAD

**Issue by wiz561** [EELV-fr/files_tree#16]
I have my owncloud install as...

"/var/www/owncloud"

and my url is

https://<foo>/owncloud

After installing the Files_tree plugin, it prompts for http authentication after login.  I have http auth for the main site but not for the owncloud subsite.  After going through the logs, I see this...

198.23.71.77 - wisniewski [06/Jun/2013:11:19:35 -0500] "GET /index.php/apps/files?dir= HTTP/1.1" 404 628 "https://<foo>/owncloud/index.php/apps/files" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0"

After a quick search through source, I believe the files_tree is not adding the subdirectory "owncloud" to the front of the URL.

**Comment by bastienho** [comment]
fixed in v0.6.8
