### ISSUE TITLE
Install error:  Integrity constraint violation

### ISSUE THREAD

**Issue by roger-wilco** [EELV-fr/files_tree#8]
Hi, 
i tried to install the app on owncloud version: 5.0.4 but get an error.
The app was downloadet directly from github - version is: 0.6.0

The error is: 
{"app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/installer.php#415","level":2,"time":1365677602}
{"app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/installer.php#418","level":2,"time":1365677602}
{"app":"PHP","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'appid' cannot be null at \/var\/www\/owncloud\/lib\/db.php#965","level":4,"time":1365677602}

Any idea why it doesnt work?

**Comment by bastienho** [comment]
This issue has been reported in the app store. 
There also is a global ticket in owncloud apps because they're is other apps concerned.

**Comment by bastienho** [comment]
The global ticket :
https://github.com/owncloud/apps/issues/685
