### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by Mokkujin** [EELV-fr/files_tree#9]
Is it possible to limit the cpu usage , i report this question in apps.owncloud.com as well but here is the bugtracker ;)

This is an good app but is it possible to limit the cpu usage , we have an Quadcore 4 x 3 GHZ Server and if anyone click "Refresh File Tree" one of our cpu cores is at 100 percent. We have a lot of users on our cloud so if 4 people click the refresh button the server do not response until the file tree is rebuild.

OC : 5.0.5
OS : Debian 6 64Bit

**Comment by bastienho** [comment]
The version 0.6.5 Scan only opened folders, increases performances
can you test with this version please ?

**Comment by bastienho** [comment]
I consider the issue resolved with v0.6.5
